### ISSUE TITLE
[BUG]: EMA CROSS strategy and settings for "EMA_cross_candles" does not work

### ISSUE THREAD

**Issue by gpumlov** [taniman/profit-trailer#1163]
Hi,

I am using following EMA cross settings:

EMA_period = 300
EMA_1 = 24
EMA_2 = 3
EMA_cross_candles = 3

This means bot should only buy after the fourth candle is forming as stated in the wiki "If fast EMA just crossed up the slow EMA in the last cross candles setup, excluding current one."

From the figure below  you can see that the bot bought on on the second candle already. This happed at least for two pairs.

![botbuy](https://user-images.githubusercontent.com/36531916/36368973-db2e1178-1559-11e8-8431-42746c782138.png)
![botbuy1](https://user-images.githubusercontent.com/36531916/36368974-db46a74c-1559-11e8-867b-d891abeffe1f.png)

Many thanks commeting if I am understanding EMA cross in a wrong way.

**Comment by WayneDanielSinclair** [comment]
To me that is how it should be working, that's how I understand the docs anyway, but it seems to buy whenever it wants after the cross
https://github.com/taniman/profit-trailer/issues/1124

**Comment by IceHaus151** [comment]
If you have 3 candles as your setting it means; exlcuding the current candle, if the fast ema crosses the slow ema within the PAST 3 candles ( last three 5minute candles by your settings) and is within your spread values, the bot will buy the coin. Thats how I understand it is supposed to work. The bot looks back. So if fast crosses slow, itll look back up to your candle value (excluding current candle) and then only buy if the spread between the 2 emas is within your range.

**Comment by WayneDanielSinclair** [comment]
Yes that's how I understand it, however, in the past 24 hours, my bot has bought on the 4th, 5th and 11th candles after the cross. My candle setting is set to 2.

**Comment by IceHaus151** [comment]
Yeah ive abandoned the EMACROSS as it just wasnt quite working as I wanted it to. I havent seen it buy that late before.  Make sure your indicators set up has the same candle values as your pairs buy strategy.

**Comment by WayneDanielSinclair** [comment]
I didn't realise there was a candles setting in pairs? I can't see it in the wiki, what is the setting name?

**Comment by IceHaus151** [comment]
The wiki actually gives misleading information on their examples

![image](https://user-images.githubusercontent.com/35858420/36396176-b6011608-158a-11e8-89b2-25844d6d0e30.png)

**Comment by IceHaus151** [comment]
ALL_buy_strategy = EMACROSS
ALL_buy_value = 1
ALL_buy_value_limit = 2
EMA_cross_candles = 4

so for example your buy settings in PAIRS could look like this 

then in INDICATORS I just make sure the Cross Candles setting matches. I dont know if it matters or not, really. i just do it that way so theres no confusion. It seems to buy within my parameters, its just I have yet to find the sweet spot for candle time length and ema length settings to avoid getting too many bags. Trial and error

**Comment by taniman** [comment]
there is no EMA_cross_candles for paits.properties

the correct definition is. the bot will buy if the crossed happenend somewhere in the amount of candles you specified. 

so the cross happend at 2pm on a 5 minute candle. you specified 3 candles to look back
it's now 2:05
so the bot looks at 2pm, 1:55, 1:50 candles. 

Did the cross happened on one of these times? Yes the cross happened on 2pm. So we buy.

**Comment by IceHaus151** [comment]
Thanks for the clarification

**Comment by WayneDanielSinclair** [comment]
So there's definitely a bug then, as I have said, I've had buys on the 4th 5th and 11th candles with an ema candles cross setting of 2.

**Comment by Sereglaith** [comment]
@WayneDanielSinclair I have experienced the same behavior with the same setting.  Do you use ProfitFeeder?  I have turned mine off for now because it felt like every time the pairs file was modified it would increase the chances it would make an incorrect buy.  I have also experienced this strategy go into a bad state (incorrect buys) with manual updates to the buy values and limits and EMA speeds.  I generally restart PT whenever I make changes now.

@taniman Thanks for the recent addition of the rebuy_timeout.  It seems to have been working well last night with v18.

**Comment by WayneDanielSinclair** [comment]
No I'm not using profit feeder. I'll try the suggestion of restarting when
I change files.

**Comment by Steven-Licari** [comment]
I'm also having issues with EMAcross I did get it work and it was freaking awesome using these settings but when I got home and charted out some of the days big gainers I realized that my bot had missed several trades, can you please help?

Pairs

#EMACROSS TEST
All_buy_strategy = EMACROSS
ALL_buy_value = 0.3
ALL_trailing_buy = 0.15

ALL_sell_strategy = GAIN
ALL_sell_value = 2

Indicators

EMA_period = 60
EMA_1 = 34
EMA_2 = 13
EMA_cross_candles = 2

**Comment by mattbuster** [comment]
I think there must be an issue too because for me PT is buying after the specified candle window and sometimes buys before the spread value is met.

**Comment by TehKamiCake** [comment]
Same issue, bot was set to buy between .08 and 1.8 with range 4 candles(EMACROSS).
By my count first buy was around 3.4 and candles were past 4

![bot](https://user-images.githubusercontent.com/36755904/36581265-c6d82006-1874-11e8-8eab-a5d6402a8381.png)

**Comment by WayneDanielSinclair** [comment]
Yes there is definitely an issue, I'm glad it's not just me I was starting to think I couldn't read charts! Hopefully the developers will see this and respond.

**Comment by mattbuster** [comment]
apparently, the issue should be fixed in the latest release.

**Comment by WayneDanielSinclair** [comment]
It would be nice to hear that from the developer. They always deny there is
a problem whenever this issue is raised.

**Comment by taniman** [comment]
@WayneDanielSinclair No issue was denied. I ha e confirmed multiple times to be investigating. So there is no need for accusations. 

This problem and many other simialr charting problems has been fixed in 1.2.6.19 and it says so in the release notes. Nothing is being hidden.

**Comment by WayneDanielSinclair** [comment]
Great, thanks.

**Comment by gpumlov** [comment]
Many thanks solving this ...I will test it with new version and comment if the strategy now works ...

**Comment by ochiengj** [comment]
I downloaded the new version 1.2.6.19. I have tried it again for a few hour. Did not work. I'm using almost all pairs, 100 volume and up. On Binance. I use trading view to monitor when a cross happens. 

It should work but it still does not. Here is my setting. Very loose. 

ALL_buy_strategy = EMACROSS
ALL_buy_value = 0.02
ALL_buy_value_limit = 3
EMA_cross_candles = 4

INDICATORS
EMA_period = 300
EMA_1 = 15
EMA_2 = 3

**Comment by Steven-Licari** [comment]
Hey man I'm using EMACross so far it's been pretty hit and miss but mostly miss....  To make it work move the EMA_cross_candles = X under your indicator file. that will get it working.  I'm not sure what the all_buy_value_limit is and I am not using it.

One other word of advise is change your EMA_period to 60, the reason I say that is that if you make a purchase and your coin is sold in a timeframe under 5 minutes your bot will buy it again generally the second purchase will shoot you in the foot and you will be left with a bad bag.  

I've asked several time for the PT team to add a sell at EMAcross but I get no response from their support.  I keep telling everyone if we had the ability to buy at the EMAcross and sell at the close of the EMAcross we wouldn't need profit feeder or PT magic and we would all be rich because our daily profits would be more in line with 5-7% instead of 1-2%  but it seems as if no one is listening.

**Comment by Steven-Licari** [comment]
Hey's my settings 

#Pairs File
All_buy_strategy = EMACROSS
ALL_buy_value = 0.3
ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_trailing_profit = .5


ALL_DCA_enabled = -4

#indicators
EMA_period = 60
EMA_1 = 34
EMA_2 = 13
EMA_cross_candles = 2

**Comment by gpumlov** [comment]
I was not aware you can use 60 seconds interval. Is it possible as in the wiki it only gives examples for 300 (5 minutes) interval only.

**Comment by TehKamiCake** [comment]
Thanks for the Update, seems to be going with out a problem

**Comment by Steven-Licari** [comment]
the time interval is according to the available time intervals present for that exchange
